# MangoHud config — eltobsjr

# Posição: canto superior esquerdo
position=top-left

# Visual
background_alpha=0.5
font_size=20
text_color=FFFFFF
background_color=020202
gpu_color=2E9762
cpu_color=2E97CB
vram_color=AD64C1
ram_color=C26693
wine_color=EB5B5B
frame_timing_color=00FF00

# O que mostrar
fps
gpu_stats
gpu_temp
gpu_mem_used
cpu_stats
cpu_temp
ram
time
frame_timing=1

# Integração com GameMode
gamemode
